/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.swing;

import exception.PamException;
import java.util.HashMap;
import java.util.List;
import java.util.Properties;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import jpa.Employe;
import metier.IMetierLocal;

/**
 *
 * @author j.fasquel
 */
public class PamSwingLocal extends javax.swing.JFrame {

    /**
     * Creates new form PamSwing
     */
    public PamSwingLocal() {
        initComponents();
        doMyInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxNom = new javax.swing.JComboBox<>();
        jButtonCalcul = new javax.swing.JButton();
        jLabelNom = new javax.swing.JLabel();
        jLabelJours = new javax.swing.JLabel();
        jTextFieldSalaireNet = new javax.swing.JTextField();
        jTextFieldJours = new javax.swing.JTextField();
        jTextFieldHeures = new javax.swing.JTextField();
        jLabelHeures = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxNom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonCalcul.setText("Salaire");
        jButtonCalcul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculActionPerformed(evt);
            }
        });

        jLabelNom.setText("Employé");

        jLabelJours.setText("Jours travaillés");

        jTextFieldSalaireNet.setText("jTextField3");

        jTextFieldJours.setText("jTextField5");

        jTextFieldHeures.setText("jTextField1");

        jLabelHeures.setText("Heures travaillées");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelHeures)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelJours))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCalcul)
                            .addComponent(jComboBoxNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldHeures, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldJours, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldSalaireNet, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jLabelHeures)
                    .addComponent(jLabelJours))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHeures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSalaireNet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalcul))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalculActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculActionPerformed
        // TODO add your handling code here:
        String selected_nom = (String)(jComboBoxNom.getSelectedItem());
        int selected_nbjours= Integer.parseInt(jTextFieldHeures.getText());
        int selected_nbheures= Integer.parseInt(jTextFieldJours.getText());
        String ss=nom2ss.get(selected_nom);
        try
        {
        double salaire_net=metier.calculerFeuilleSalaire(ss,selected_nbjours, selected_nbheures).getElementsSalaire().getSalaireNet();
        jTextFieldSalaireNet.setText(Double.toString(salaire_net));
        }
        catch(NamingException ex)
        {
            return;
        }
    }//GEN-LAST:event_jButtonCalculActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PamSwingLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PamSwingLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PamSwingLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PamSwingLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PamSwingLocal().setVisible(true);
            }
        });
    }

    public final void doMyInit()
    {
        try
        {
        // instanciation couche [metier]
        Properties properties = new Properties();
        properties.setProperty(Context.INITIAL_CONTEXT_FACTORY, "org.apache.openejb.client.LocalInitialContextFactory");
        // initialisation du contexte JNDI avec les propriÃ©tÃ©s prÃ©cÃ©dentes
        InitialContext initialContext = new InitialContext(properties);

        metier=(IMetierLocal)initialContext.lookup("MetierLocal");
        List<Employe> allemployes = metier.findAllEmployes();
        //Clear
        jTextFieldHeures.setText("");
        jTextFieldSalaireNet.setText("");
        jTextFieldJours.setText("");
        jComboBoxNom.removeAllItems();
        for( Employe t : allemployes )
            {
                nom2ss.put(t.getNom(), t.getSs());
                System.out.println(nom2ss.get(t.getNom()));
                jComboBoxNom.addItem(t.getNom());
            }
        }
        catch (PamException ex)
        {
            //jTextAreaStatus.setText(ex.toString());
        return;
        }
        catch( NamingException ex)
        {
            return;
        }
        
    }
    //Variables personnelles
    private IMetierLocal metier;
    private HashMap<String,String> nom2ss = new HashMap<String,String>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcul;
    private javax.swing.JComboBox<String> jComboBoxNom;
    private javax.swing.JLabel jLabelHeures;
    private javax.swing.JLabel jLabelJours;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JTextField jTextFieldHeures;
    private javax.swing.JTextField jTextFieldJours;
    private javax.swing.JTextField jTextFieldSalaireNet;
    // End of variables declaration//GEN-END:variables
}
